/* Pyrocene cinematic replay. The event log is the outcome; this file only renders it. */
(() => {
  'use strict';
  const $=s=>document.querySelector(s),T=window.THREE;
  const ui={canvas:$('#world'),loader:$('#loader'),loadText:$('#loadText'),loadBar:$('#loadBar'),fileButton:$('#fileButton'),fileInput:$('#fileInput'),
    health:$('#health'),night:$('#nightReadout'),chapter:$('#chapter'),line:$('#line'),detail:$('#detail'),telemetry:$('#telemetry'),telemetryBody:$('#telemetryBody'),
    controls:$('#controls'),play:$('#play'),playIcon:$('#playIcon'),scrub:$('#scrub'),clock:$('#clock'),trackLabel:$('#trackLabel'),sound:$('#sound'),fuel:$('#fuel'),restart:$('#restart'),
    inspect:$('#inspect'),inspectTitle:$('#inspectTitle'),facts:$('#facts'),inspectNote:$('#inspectNote'),toast:$('#toast'),webglError:$('#webglError')};
  if(!T){ui.webglError.hidden=false;return}
  const CELL=4.6,MAX_FLAME=2200,MAX_SMOKE=1200,UP=new T.Vector3(0,1,0);
  const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),ease=t=>t*t*(3-2*t),smoother=t=>t*t*t*(t*(t*6-15)+10);
  const hash=s=>{let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0)/4294967295};
  const h2=(x,z)=>hash(`${Math.floor(x*43)}:${Math.floor(z*47)}`),copy=b=>new Map([...b].map(([k,v])=>[k,{...v}]));
  let model,world,scenes=[],total=1,playhead=0,playing=true,last=performance.now(),inspector=false,inspectTurn=0,manualFuel=false;
  let sceneNow=null,sceneProgress=0,audio=null,drag=null,orbit={yaw:.72,pitch:.46,distance:47};

  function pos(name){const m=/^([A-Z]+)(\d+)$/.exec(name);let c=0;for(const ch of m[1])c=c*26+ch.charCodeAt(0)-64;return{c:c-1,r:+m[2]-1}}
  function cellName(c,r){if(c<0||r<0||c>=model.cols||r>=model.rows)return'';let n=c+1,s='';while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26)}return s+(r+1)}
  const coverOf=v=>String(v).startsWith('invasive')?'invasive':v;
  const stageOf=v=>v==='invasive_young'?1:v==='invasive_spreading'?2:v==='invasive_thick'?3:0;
  function worldPos(name){const p=pos(name);return new T.Vector3((p.c-(model.cols-1)/2)*CELL,0,(p.r-(model.rows-1)/2)*CELL)}
  function direction(cells){if(!cells.length)return'the forest';let r=0,c=0;for(const n of cells){const p=pos(n);r+=p.r;c+=p.c}r/=cells.length;c/=cells.length;const ns=r<model.rows*.36?'north':r>model.rows*.64?'south':'',ew=c<model.cols*.36?'west':c>model.cols*.64?'east':'';return ns&&ew?`the ${ns} ${ew}`:ns||ew?`the ${ns||ew}`:'the centre'}
  function centroid(cells){if(!cells?.length)return new T.Vector3();const v=new T.Vector3();for(const n of cells)v.add(worldPos(n));return v.multiplyScalar(1/cells.length)}
  function apply(board,changes,turn){const b=copy(board);for(const ch of changes){const old=b.get(ch.cell)||{cell:ch.cell};const cover=coverOf(ch.to);b.set(ch.cell,{...old,cover,stage:stageOf(ch.to),born:cover==='invasive'&&old.cover!=='invasive'?turn:old.born})}return b}
  function splitRound(r){const changes=r.landscape_changes||[],burned=new Set((r.fire||{}).burned_cells||[]);let cut=changes.length;while(cut&&burned.has(changes[cut-1].cell)&&changes[cut-1].to==='bare')cut--;return{before:changes.slice(0,cut),fire:changes.slice(cut)}}
  function connected(board,start){
    const fuel=new Set([...board].filter(([,c])=>c.cover==='invasive').map(([n])=>n));if(!fuel.size)return new Set();
    const walk=n=>{const seen=new Set([n]),q=[n];while(q.length){const x=q.pop(),p=pos(x);for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){if(!dr&&!dc)continue;const nn=cellName(p.c+dc,p.r+dr);if(fuel.has(nn)&&!seen.has(nn)){seen.add(nn);q.push(nn)}}}return seen};
    if(fuel.has(start))return walk(start);let best=new Set(),done=new Set();for(const n of fuel){if(done.has(n))continue;const got=walk(n);got.forEach(x=>done.add(x));if(got.size>best.size)best=got}return best;
  }
  function healthFrom(board){let n=0,land=0;for(const c of board.values()){if(!['water','village'].includes(c.cover))land++;if(c.cover==='native')n++}return land?Math.round(n/land*100):0}
  function buildModel(d){
    const g=d.game||{},rounds=d.rounds||[];if(!g.terrain||!g.cols||!g.rows)throw Error('This file does not contain a current Pyrocene landscape record.');
    const initial=new Map(g.terrain.map(c=>[c.cell,{...c,born:c.cover==='invasive'?0:null}]));
    model={cols:g.cols,rows:g.rows,initial,rounds:[],ending:g.ending||{},startHealth:rounds[0]?.health_before??healthFrom(initial),finalHealth:g.ending?.health??rounds.at(-1)?.health??healthFrom(initial),hillPoints:[]};
    for(const [n,c] of initial)if(c.hill){const p=pos(n);model.hillPoints.push({x:(p.c-(g.cols-1)/2)*CELL,z:(p.r-(g.rows-1)/2)*CELL})}
    let board=copy(initial),lines=new Set();
    for(const r of rounds){const parts=splitRound(r),linesBefore=new Set(lines);if(r.resilience?.type==='fire_line')for(const n of r.resilience.cells||[])lines.add(n);const before=copy(board),pre=apply(before,parts.before,r.turn),end=apply(pre,parts.fire,r.turn);model.rounds.push({raw:r,before,pre,end,lines:new Set(lines),linesBefore,newFuel:parts.before.filter(c=>coverOf(c.to)==='invasive'&&coverOf(c.from)!=='invasive').map(c=>c.cell),recovered:parts.before.filter(c=>c.to==='native').map(c=>c.cell)});board=end}
    model.final=board;model.majorIndex=pickIndex(x=>x.raw.fire?.burned_cells?.length||0);model.defenseIndex=pickIndex(x=>x.raw.fire?.blocked_edges?.length||0);model.waterIndex=pickIndex(x=>x.raw.fire?.capped_by_water?(x.raw.fire.burned_cells?.length||1):0);model.criticalIndex=model.rounds.findIndex(x=>(x.raw.fire?.severity||0)>=3);
    if(model.majorIndex>=0){const x=model.rounds[model.majorIndex];x.corridor=connected(x.pre,x.raw.fire?.ignition_cell)}if(model.criticalIndex>=0){const x=model.rounds[model.criticalIndex];x.criticalCorridor=connected(x.before,x.raw.fire?.ignition_cell)}
  }
  function pickIndex(score){let ix=-1,best=0;model.rounds.forEach((x,i)=>{const n=score(x);if(n>best){best=n;ix=i}});return ix}

  class Landscape {
    constructor(){
      this.scene=new T.Scene();this.scene.background=new T.Color(0x020504);this.scene.fog=new T.FogExp2(0x07100c,.0125);
      this.camera=new T.PerspectiveCamera(34,innerWidth/innerHeight,.1,420);this.camera.position.set(42,32,48);this.look=new T.Vector3();
      try{this.renderer=new T.WebGLRenderer({canvas:ui.canvas,antialias:true,powerPreference:'high-performance',alpha:false,stencil:false})}catch(e){ui.webglError.hidden=false;throw e}
      this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.65));this.renderer.setSize(innerWidth,innerHeight,false);this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=.78;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;
      this.dummy=new T.Object3D();this.cellNames=[...model.initial.keys()];this.fireAmount=0;this.makeLights();this.makeGround();progress(28);this.makeWaterRoadsHomes();progress(40);this.makeVegetation();progress(68);this.makePerimeter();progress(78);this.makeAtmosphere();this.makeFire();this.makeScan();this.makeTrenches();progress(92);this.resize=()=>{this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.65));this.renderer.setSize(innerWidth,innerHeight,false)};addEventListener('resize',this.resize);
    }
    makeLights(){
      this.scene.add(new T.HemisphereLight(0x5d8175,0x080705,.62));const moon=new T.DirectionalLight(0x9ec7c1,2.2);moon.position.set(-32,58,-28);moon.castShadow=true;moon.shadow.mapSize.set(2048,2048);moon.shadow.camera.left=-70;moon.shadow.camera.right=70;moon.shadow.camera.top=55;moon.shadow.camera.bottom=-55;moon.shadow.bias=-.0008;this.scene.add(moon);
      this.fireLight=new T.PointLight(0xff6b27,0,38,1.6);this.fireLight.position.set(0,5,0);this.scene.add(this.fireLight);const rim=new T.DirectionalLight(0xd4b27c,.65);rim.position.set(45,24,32);this.scene.add(rim);
    }
    terrainY(x,z){let y=.22*Math.sin(x*.19)+.16*Math.cos(z*.23)+.11*Math.sin((x+z)*.41)+.07*(h2(x,z)-.5),hill=0;for(const p of model.hillPoints){const d2=(x-p.x)**2+(z-p.z)**2;hill=Math.max(hill,Math.exp(-d2/(CELL*CELL*2.3)))}return y+hill*1.35}
    makeGround(){
      const w=model.cols*CELL+24,d=model.rows*CELL+24,sx=model.cols*5,sz=model.rows*5,g=new T.PlaneGeometry(w,d,sx,sz);g.rotateX(-Math.PI/2);const p=g.attributes.position,colors=new Float32Array(p.count*3);this.groundCells=[];
      for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getZ(i);p.setY(i,this.terrainY(x,z));const warpX=(Math.sin(z*.61)+Math.sin(z*.19+x*.13))*CELL*.13,warpZ=(Math.sin(x*.53)+Math.cos(z*.17-x*.11))*CELL*.13,c=clamp(Math.floor((x+warpX)/CELL+model.cols/2),0,model.cols-1),r=clamp(Math.floor((z+warpZ)/CELL+model.rows/2),0,model.rows-1);this.groundCells.push(cellName(c,r));colors[i*3]=.1;colors[i*3+1]=.16;colors[i*3+2]=.1}g.setAttribute('color',new T.BufferAttribute(colors,3));g.computeVertexNormals();this.groundGeo=g;
      const m=new T.MeshStandardMaterial({vertexColors:true,roughness:.94,metalness:.02});this.ground=new T.Mesh(g,m);this.ground.receiveShadow=true;this.scene.add(this.ground);
      const under=new T.Mesh(new T.CylinderGeometry(Math.max(w,d)*.73,Math.max(w,d)*.76,2.6,64),new T.MeshStandardMaterial({color:0x14120d,roughness:1}));under.position.y=-1.55;under.scale.z=d/w;this.scene.add(under);
    }
    makeWaterRoadsHomes(){
      this.staticGroup=new T.Group();this.scene.add(this.staticGroup);const waterMat=new T.MeshPhysicalMaterial({color:0x285a58,roughness:.18,metalness:.16,transparent:true,opacity:.83,clearcoat:1,clearcoatRoughness:.12}),roadMat=new T.MeshStandardMaterial({color:0x776954,roughness:1}),wallMat=new T.MeshStandardMaterial({color:0xbbb098,roughness:.9}),roofMat=new T.MeshStandardMaterial({color:0x663c2f,roughness:.8}),windowMat=new T.MeshBasicMaterial({color:0xffbd62});
      for(const [n,c] of model.initial){const p=worldPos(n),y=this.terrainY(p.x,p.z);if(c.cover==='water'){const m=new T.Mesh(new T.PlaneGeometry(CELL*1.08,CELL*1.08),waterMat);m.rotation.x=-Math.PI/2;m.position.set(p.x,y+.12,p.z);m.receiveShadow=true;this.staticGroup.add(m)}
        if(c.road){const q=pos(n),lr=model.initial.get(cellName(q.c-1,q.r))?.road||model.initial.get(cellName(q.c+1,q.r))?.road,m=new T.Mesh(new T.PlaneGeometry(CELL*1.12,CELL*.72),roadMat);m.rotation.x=-Math.PI/2;m.rotation.z=lr?0:Math.PI/2;m.position.set(p.x,y+.15,p.z);m.receiveShadow=true;this.staticGroup.add(m)}
        if(c.cover==='village'){for(let k=0;k<2;k++){const house=new T.Group(),box=new T.Mesh(new T.BoxGeometry(1.35,.95,1.2),wallMat),roof=new T.Mesh(new T.ConeGeometry(1.08,.72,4),roofMat),win=new T.Mesh(new T.PlaneGeometry(.28,.25),windowMat);box.position.y=.48;box.castShadow=true;roof.position.y=1.25;roof.rotation.y=Math.PI/4;roof.castShadow=true;win.position.set(0,.58,.606);house.add(box,roof,win);house.position.set(p.x+(k?1:-1)*.82,y+.12,p.z+(k?-.45:.4));house.rotation.y=(hash(n+k)-.5)*.45;this.staticGroup.add(house)}}
      }
    }
    makeVegetation(){
      const slots=5,count=this.cellNames.length*slots,bslots=10,bcount=this.cellNames.length*bslots;this.treeMeta=[];this.bushMeta=[];
      const trunkMat=new T.MeshStandardMaterial({color:0x544638,roughness:1,vertexColors:true}),leafMat=new T.MeshStandardMaterial({color:0x244d36,roughness:.92,vertexColors:true}),leafMat2=new T.MeshStandardMaterial({color:0x315d3f,roughness:.92,vertexColors:true}),bushMat=new T.MeshStandardMaterial({color:0x5e2938,roughness:.96,vertexColors:true}),deadMat=new T.MeshStandardMaterial({color:0x171411,roughness:1,vertexColors:true});
      this.trunks=new T.InstancedMesh(new T.CylinderGeometry(.09,.14,1,7),trunkMat,count);this.canopy=new T.InstancedMesh(new T.IcosahedronGeometry(.82,2),leafMat,count);this.canopyTop=new T.InstancedMesh(new T.IcosahedronGeometry(.58,2),leafMat2,count);this.bushes=new T.InstancedMesh(new T.IcosahedronGeometry(.47,1),bushMat,bcount);this.deadwood=new T.InstancedMesh(new T.CylinderGeometry(.035,.1,1,6),deadMat,count);
      for(const m of [this.trunks,this.canopy,this.canopyTop,this.bushes,this.deadwood]){m.instanceMatrix.setUsage(T.DynamicDrawUsage);m.castShadow=m===this.trunks||m===this.canopy;m.receiveShadow=true;this.scene.add(m)}
      let i=0;for(const n of this.cellNames){const cp=worldPos(n);for(let k=0;k<slots;k++,i++){const a=hash(n+'treea'+k)*Math.PI*2,r=Math.sqrt(hash(n+'treer'+k))*CELL*.39,x=cp.x+Math.cos(a)*r,z=cp.z+Math.sin(a)*r;this.treeMeta.push({cell:n,x,z,y:this.terrainY(x,z),h:2.8+hash(n+'h'+k)*3.2,s:.72+hash(n+'s'+k)*.6,phase:hash(n+'p'+k)*6.28});const col=new T.Color().setHSL(.31+hash(n+'tc'+k)*.045,.34,.18+hash(n+'tl'+k)*.08);this.canopy.setColorAt(i,col);this.canopyTop.setColorAt(i,col.clone().offsetHSL(.015,.04,.035));this.trunks.setColorAt(i,new T.Color(0x4b4136));this.deadwood.setColorAt(i,new T.Color().setScalar(.04+hash(n+'d'+k)*.035))}}
      i=0;for(const n of this.cellNames){const cp=worldPos(n);for(let k=0;k<bslots;k++,i++){const a=hash(n+'ba'+k)*Math.PI*2,r=Math.sqrt(hash(n+'br'+k))*CELL*.42,x=cp.x+Math.cos(a)*r,z=cp.z+Math.sin(a)*r;this.bushMeta.push({cell:n,x,z,y:this.terrainY(x,z),s:.55+hash(n+'bs'+k)*.75,phase:hash(n+'bp'+k)*6.28});this.bushes.setColorAt(i,new T.Color().setHSL(.94+hash(n+'bc'+k)*.035,.38,.16+hash(n+'bl'+k)*.07))}}
      for(const m of [this.trunks,this.canopy,this.canopyTop,this.bushes,this.deadwood])if(m.instanceColor)m.instanceColor.needsUpdate=true;
    }
    makePerimeter(){
      const count=460,geo=new T.ConeGeometry(.75,5.8,7),mat=new T.MeshStandardMaterial({color:0x101d16,roughness:1,transparent:true,opacity:.9}),mesh=new T.InstancedMesh(geo,mat,count),w=model.cols*CELL/2,d=model.rows*CELL/2;
      for(let i=0;i<count;i++){const side=i%4,u=hash('edge'+i),far=4+hash('far'+i)*21;let x,z;if(side<2){x=(u-.5)*(w*2+45);z=(side?1:-1)*(d+far)}else{x=(side===2?-1:1)*(w+far);z=(u-.5)*(d*2+45)}const h=3.5+hash('eh'+i)*6;this.dummy.position.set(x,this.terrainY(x,z)+h/2,z);this.dummy.scale.set(.7+hash('es'+i),h/5.8,.7+hash('ez'+i));this.dummy.rotation.y=hash('er'+i)*6.28;this.dummy.updateMatrix();mesh.setMatrixAt(i,this.dummy.matrix)}mesh.castShadow=true;this.scene.add(mesh);this.perimeter=mesh;
    }
    softTexture(inner,outer){const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d'),g=x.createRadialGradient(64,64,1,64,64,62);g.addColorStop(0,inner);g.addColorStop(.35,inner);g.addColorStop(1,outer);x.fillStyle=g;x.fillRect(0,0,128,128);return new T.CanvasTexture(c)}
    makeAtmosphere(){
      const n=4200,a=new Float32Array(n*3),col=new Float32Array(n*3);for(let i=0;i<n;i++){a[i*3]=(hash('px'+i)-.5)*(model.cols*CELL+80);a[i*3+1]=hash('py'+i)*18+.2;a[i*3+2]=(hash('pz'+i)-.5)*(model.rows*CELL+70);const q=.18+hash('pc'+i)*.25;col[i*3]=q*.74;col[i*3+1]=q;col[i*3+2]=q*.8}const g=new T.BufferGeometry();g.setAttribute('position',new T.BufferAttribute(a,3));g.setAttribute('color',new T.BufferAttribute(col,3));this.dust=new T.Points(g,new T.PointsMaterial({size:.075,vertexColors:true,transparent:true,opacity:.42,depthWrite:false,blending:T.AdditiveBlending}));this.scene.add(this.dust);
    }
    makeFire(){
      const fp=new Float32Array(MAX_FLAME*3),fc=new Float32Array(MAX_FLAME*3),sp=new Float32Array(MAX_SMOKE*3);this.fireGeo=new T.BufferGeometry();this.fireGeo.setAttribute('position',new T.BufferAttribute(fp,3));this.fireGeo.setAttribute('color',new T.BufferAttribute(fc,3));this.fireGeo.setDrawRange(0,0);this.flames=new T.Points(this.fireGeo,new T.PointsMaterial({size:1.45,map:this.softTexture('#fffbd2','#ff3d0000'),vertexColors:true,transparent:true,opacity:.96,depthWrite:false,blending:T.AdditiveBlending,sizeAttenuation:true}));this.flames.renderOrder=8;this.scene.add(this.flames);
      this.smokeGeo=new T.BufferGeometry();this.smokeGeo.setAttribute('position',new T.BufferAttribute(sp,3));this.smokeGeo.setDrawRange(0,0);this.smoke=new T.Points(this.smokeGeo,new T.PointsMaterial({size:4.6,map:this.softTexture('#706d66aa','#1e211e00'),color:0x625f58,transparent:true,opacity:.24,depthWrite:false,sizeAttenuation:true}));this.smoke.renderOrder=7;this.scene.add(this.smoke);
      const mp=new Float32Array(700*3);this.mistGeo=new T.BufferGeometry();this.mistGeo.setAttribute('position',new T.BufferAttribute(mp,3));this.mistGeo.setDrawRange(0,0);this.mist=new T.Points(this.mistGeo,new T.PointsMaterial({size:2.1,map:this.softTexture('#d9ffffbb','#a4e8e800'),color:0xbce8e5,transparent:true,opacity:.32,depthWrite:false,blending:T.AdditiveBlending}));this.scene.add(this.mist);
    }
    makeScan(){
      const mat=new T.ShaderMaterial({transparent:true,side:T.DoubleSide,depthWrite:false,uniforms:{time:{value:0},alpha:{value:0}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'varying vec2 vUv;uniform float time;uniform float alpha;void main(){float lines=smoothstep(.47,.5,abs(fract(vUv.y*70.0+time*.7)-.5));float edge=smoothstep(.42,.5,abs(vUv.x-.5));vec3 c=mix(vec3(.18,.6,.62),vec3(.85,.67,.35),vUv.y);gl_FragColor=vec4(c,alpha*(.035+lines*.1+edge*.3));}'});this.scan=new T.Mesh(new T.PlaneGeometry(model.rows*CELL+4,16),mat);this.scan.rotation.y=Math.PI/2;this.scan.position.y=8;this.scan.visible=false;this.scene.add(this.scan);const e=new T.EdgesGeometry(this.scan.geometry),lm=new T.LineBasicMaterial({color:0x79c5ce,transparent:true,opacity:.3});this.scanEdge=new T.LineSegments(e,lm);this.scan.add(this.scanEdge);
      this.corridorGroup=new T.Group();this.corridorKey='';this.corridorMat=new T.SpriteMaterial({map:this.flames.material.map,color:0xe7ba6b,transparent:true,opacity:.12,depthWrite:false,blending:T.AdditiveBlending});this.scene.add(this.corridorGroup);
    }
    makeTrenches(){
      const all=new Set();for(const x of model.rounds)for(const n of x.lines)all.add(n);this.trenches=new Map();const mat=new T.MeshStandardMaterial({color:0x1b1712,roughness:1}),edgeMat=new T.MeshBasicMaterial({color:0xc9b083});
      for(const n of all){const p=worldPos(n),q=pos(n),horiz=[cellName(q.c-1,q.r),cellName(q.c+1,q.r)].some(x=>all.has(x)),g=new T.Group(),cut=new T.Mesh(new T.BoxGeometry(CELL*.9,.17,.72),mat),edge=new T.Mesh(new T.BoxGeometry(CELL*.94,.035,.08),edgeMat);cut.rotation.y=horiz?0:Math.PI/2;edge.rotation.y=cut.rotation.y;edge.position.z=horiz ? .41 : 0;edge.position.x=horiz ? 0 : .41;g.add(cut,edge);g.position.set(p.x,this.terrainY(p.x,p.z)+.09,p.z);g.visible=false;this.scene.add(g);this.trenches.set(n,g)}
    }
    coverWeights(name,st){const a=st.board.get(name)||{},b=st.to?.get(name)||a,p=st.to?st.mix:0,w={};w[a.cover]=(w[a.cover]||0)+1-p;w[b.cover]=(w[b.cover]||0)+p;return{w,a,b,p}}
    updateGround(st){const arr=this.groundGeo.attributes.color,from=new T.Color(),to=new T.Color(),out=new T.Color(),palette={native:0x294a31,invasive:0x48292e,bare:0x17130f,water:0x214b49,village:0x625342};for(let i=0;i<arr.count;i++){const n=this.groundCells[i],a=st.board.get(n)||{},b=st.to?.get(n)||a,p=st.to?st.mix:0;from.setHex(palette[a.cover]||0x263c28);to.setHex(palette[b.cover]||0x263c28);out.copy(from).lerp(to,p);if(st.fuel&&b.cover==='invasive')out.lerp(new T.Color(0x8e5631),.42);if(st.fuel&&b.cover!=='invasive'&&a.cover!=='invasive')out.multiplyScalar(.43);arr.setXYZ(i,out.r,out.g,out.b)}arr.needsUpdate=true}
    updateVegetation(st,time,turn){
      let i=0;for(const m of this.treeMeta){const x=this.coverWeights(m.cell,st),native=x.w.native||0,bare=x.w.bare||0,y=m.y,s=m.s*native,wind=Math.sin(time*.75+m.phase)*.025;this.dummy.position.set(m.x,y+m.h*.5*native,m.z);this.dummy.rotation.set(wind,0,-wind*.7);this.dummy.scale.set(s,s*m.h,s);this.dummy.updateMatrix();this.trunks.setMatrixAt(i,this.dummy.matrix);this.dummy.position.y=y+m.h*.72*native;this.dummy.scale.set(s*1.7,s*1.15,s*1.7);this.dummy.updateMatrix();this.canopy.setMatrixAt(i,this.dummy.matrix);this.dummy.position.y=y+m.h*1.02*native;this.dummy.scale.set(s*1.25,s*.95,s*1.25);this.dummy.updateMatrix();this.canopyTop.setMatrixAt(i,this.dummy.matrix);this.dummy.position.set(m.x,y+.7*bare,m.z);this.dummy.rotation.set((hash(m.cell+i)-.5)*.25,0,(hash('lean'+m.cell+i)-.5)*.48);this.dummy.scale.set(.75*bare,(1.4+hash('dh'+i)*2.3)*bare,.75*bare);this.dummy.updateMatrix();this.deadwood.setMatrixAt(i,this.dummy.matrix);i++}
      i=0;for(const m of this.bushMeta){const x=this.coverWeights(m.cell,st),inv=x.w.invasive||0,c=x.b.cover==='invasive'?x.b:x.a,stage=Math.min(3,Math.max(c.stage||1,1+Math.max(0,turn-(c.born??0)))),y=m.y,s=m.s*inv*(.58+stage*.2),wind=Math.sin(time*1.1+m.phase)*.055;this.dummy.position.set(m.x,y+.24+s*.36,m.z);this.dummy.rotation.set(wind,hash('rot'+i)*6.28,wind*.6);this.dummy.scale.set(s*(1.2+hash('bx'+i)*.5),s*(.55+stage*.23),s*(1.1+hash('bz'+i)*.5));this.dummy.updateMatrix();this.bushes.setMatrixAt(i,this.dummy.matrix);i++}
      for(const m of [this.trunks,this.canopy,this.canopyTop,this.deadwood,this.bushes])m.instanceMatrix.needsUpdate=true;
    }
    updateTrenches(st){for(const[n,g]of this.trenches)g.visible=st.lines.has(n)}
    activeFire(f,p){const cells=[],waves=f?.waves||[],x=clamp(p)*waves.length;for(let i=0;i<waves.length;i++)if(i<x)for(const n of waves[i]||[])cells.push({n,wave:i,age:x-i});return cells}
    updateFire(st,time){
      const active=this.activeFire(st.fire,st.fireProgress),fp=this.fireGeo.attributes.position.array,fc=this.fireGeo.attributes.color.array,sp=this.smokeGeo.attributes.position.array,mp=this.mistGeo.attributes.position.array;let fi=0,si=0,mi=0,cx=0,cz=0;
      for(const item of active){const p=worldPos(item.n),fresh=clamp(1-item.age*.08,.25,1);cx+=p.x;cz+=p.z;if(!st.smokeOnly)for(let k=0;k<14&&fi<MAX_FLAME;k++,fi++){const q=hash(item.n+'fx'+k),a=hash(item.n+'fa'+k)*6.28,r=Math.sqrt(q)*CELL*.47,rise=(time*(1.3+hash('fr'+k)*2)+hash(item.n+'fy'+k)*5)%4.5;fp[fi*3]=p.x+Math.cos(a)*r+Math.sin(time*3+k)*.12;fp[fi*3+1]=this.terrainY(p.x,p.z)+.25+rise*(.38+.3*fresh);fp[fi*3+2]=p.z+Math.sin(a)*r;const hot=clamp(1-rise/4.5);fc[fi*3]=1;fc[fi*3+1]=.12+.75*hot;fc[fi*3+2]=.015}
        for(let k=0;k<8&&si<MAX_SMOKE;k++,si++){const a=hash(item.n+'sa'+k)*6.28,r=hash(item.n+'sr'+k)*CELL*.55,rise=(time*(.35+hash('ss'+k)*.35)+hash(item.n+'sy'+k)*9)%9;sp[si*3]=p.x+Math.cos(a)*r+rise*.13;sp[si*3+1]=this.terrainY(p.x,p.z)+1+rise;sp[si*3+2]=p.z+Math.sin(a)*r-rise*.05}
        if(st.water)for(let k=0;k<8&&mi<700;k++,mi++){const a=hash(item.n+'ma'+k)*6.28,r=hash(item.n+'mr'+k)*CELL*.8,rise=(time*.9+hash(item.n+'my'+k)*5)%5;mp[mi*3]=p.x+Math.cos(a)*r-rise*.2;mp[mi*3+1]=this.terrainY(p.x,p.z)+.5+rise*.7;mp[mi*3+2]=p.z+Math.sin(a)*r}
      }
      this.fireGeo.setDrawRange(0,fi);this.smokeGeo.setDrawRange(0,si);this.mistGeo.setDrawRange(0,mi);this.fireGeo.attributes.position.needsUpdate=this.fireGeo.attributes.color.needsUpdate=this.smokeGeo.attributes.position.needsUpdate=this.mistGeo.attributes.position.needsUpdate=true;this.smoke.material.opacity=st.smokeOnly ? .22*(1-st.local*.72) : .24;this.fireAmount=st.smokeOnly?0:active.length;
      if(active.length&&!st.smokeOnly){this.fireLight.position.set(cx/active.length,4.2,cz/active.length);this.fireLight.intensity=clamp(active.length/7,1.2,7)*(1+Math.sin(time*13)*.12)}else this.fireLight.intensity=0;
    }
    updateScan(st,time){const scanOn=['restore','growth','fuel','critical','rewind'].includes(st.kind);this.scan.visible=scanOn;this.scan.material.uniforms.time.value=time;this.scan.material.uniforms.alpha.value=scanOn ? ((st.kind==='fuel'||st.kind==='critical') ? .72 : .3) : 0;const scanProgress=st.local??.5;this.scan.position.x=(-model.cols*CELL*.5-3)+(model.cols*CELL+6)*(st.kind==='rewind'?1-scanProgress:scanProgress);this.scan.position.z=0;
      const key=st.fuel?[...st.corridor].sort().join(','):'';if(key!==this.corridorKey){this.corridorGroup.clear();this.corridorKey=key;if(key)for(const n of st.corridor){const p=worldPos(n);p.y=this.terrainY(p.x,p.z)+.18;for(let k=0;k<3;k++){const s=new T.Sprite(this.corridorMat);s.position.set(p.x+(hash(n+k)-.5)*CELL,p.y+.4+hash('cy'+n+k)*1.4,p.z+(hash('cz'+n+k)-.5)*CELL);s.scale.set(.3,.3,.3);this.corridorGroup.add(s)}}}}
    cameraShot(st,time){
      let focus=st.focus?.clone()||new T.Vector3(),pos=new T.Vector3(),fov=34;const p=st.local||0,w=model.cols*CELL,d=model.rows*CELL;
      if(inspector){focus.set(0,0,0);pos.set(Math.cos(orbit.yaw)*Math.cos(orbit.pitch)*orbit.distance,Math.sin(orbit.pitch)*orbit.distance+5,Math.sin(orbit.yaw)*Math.cos(orbit.pitch)*orbit.distance);fov=38}
      else if(st.kind==='final'){pos.set(w*.46,32,d*.68);focus.set(0,0,0);fov=31}
      else if(st.kind==='restore'){pos.set(T.MathUtils.lerp(w*.42,18,p),T.MathUtils.lerp(34,8,p),T.MathUtils.lerp(d*.62,24,p));focus.set(0,1,0);fov=32}
      else if(st.kind==='opening'){pos.set(-24+6*p,8.2,29);focus.y=1.3;fov=30}
      else if(st.kind==='growth'){const a=1.2+p*.55;pos.set(focus.x+Math.cos(a)*21,7.5,focus.z+Math.sin(a)*21);focus.y=1.1;fov=32}
      else if(st.kind==='defense'){pos.set(focus.x+10,3.8,focus.z+12);focus.y=.8;fov=30}
      else if(st.kind==='fuel'||st.kind==='critical'){pos.set(focus.x+26,25,focus.z+31);focus.y=.2;fov=28}
      else if(st.kind==='ignite'){pos.set(focus.x+8.5*(1-p*.28),2.5,focus.z+10*(1-p*.28));focus.y=.8;fov=26}
      else if(st.kind==='majorFire'){const a=.35+p*.75;pos.set(focus.x+Math.cos(a)*17,5.2,focus.z+Math.sin(a)*17);focus.y=1.4;fov=32}
      else if(st.kind==='aftermath'){pos.set(focus.x+T.MathUtils.lerp(14,31,p),T.MathUtils.lerp(6,28,p),focus.z+T.MathUtils.lerp(17,35,p));focus.y=.4;fov=31}
      else if(st.kind==='ending'){pos.set(w*.43,29,d*.63);focus.set(0,0,0);fov=31}
      else if(st.kind==='rewind'){const a=.6+p*1.2;pos.set(Math.cos(a)*46,32,Math.sin(a)*46);focus.set(0,0,0);fov=34}
      else{pos.set(32,25,40);focus.set(0,0,0)}
      if(st.kind==='majorFire'){pos.x+=Math.sin(time*19)*.08;pos.y+=Math.sin(time*23)*.055;pos.z+=Math.cos(time*17)*.07}
      const alpha=inspector ? .13 : .055;this.camera.position.lerp(pos,alpha);this.look.lerp(focus,alpha);this.camera.fov=T.MathUtils.lerp(this.camera.fov,fov,.08);this.camera.updateProjectionMatrix();this.camera.lookAt(this.look);
    }
    render(st,time,turn){this.updateGround(st);this.updateVegetation(st,time,turn);this.updateTrenches(st);this.updateFire(st,time);this.updateScan(st,time);this.cameraShot(st,time);this.dust.rotation.y=time*.004;this.renderer.toneMappingExposure=T.MathUtils.lerp(this.renderer.toneMappingExposure,this.fireAmount ? .96 : .7,.035);this.renderer.render(this.scene,this.camera)}
  }

  function add(s){s.start=scenes.length?scenes.at(-1).end:0;s.end=s.start+s.duration;scenes.push(s)}
  function makeScenes(){
    scenes=[];const starts=[...model.initial].filter(([,c])=>c.cover==='invasive').map(([n])=>n),def=model.defenseIndex,water=model.waterIndex;
    add({kind:'final',duration:4,board:model.final,health:model.finalHealth,chapter:'AFTER THE FINAL NIGHT',caption:'This is the landscape you left behind.',detail:model.ending.text||`Forest health stands at ${model.finalHealth}%.`,focusCells:[...model.final].filter(([,c])=>c.cover==='bare').map(([n])=>n)});
    add({kind:'restore',duration:3.4,a:model.final,b:model.initial,healthA:model.finalHealth,health:model.startHealth,chapter:'RECONSTRUCTION',caption:'Go back to the first night.',detail:'Every burned stand returns. Every invaded patch retreats.'});
    add({kind:'opening',duration:2.4,board:model.initial,health:model.startHealth,chapter:'NIGHT ZERO',caption:'The invaded stands begin apart.',detail:`${starts.length} squares carry lantana at the start.`,focusCells:starts});
    model.rounds.forEach((x,i)=>{const r=x.raw,fire=r.fire||{},burn=fire.burned_cells||[],major=i===model.majorIndex,special=i===def||i===water;add({kind:'growth',duration:1.45,a:x.before,b:(major||special)?x.pre:x.end,pre:x.pre,healthA:r.health_before,health:(major||special)?r.health_before:r.health,chapter:`NIGHT ${r.turn} / ${r.choice==='resilience'?'RESILIENCE':'THE VOTE'}`,caption:x.newFuel.length?`Lantana takes ${x.newFuel.length} more ${x.newFuel.length===1?'square':'squares'}.`:x.recovered.length?'Native forest returns to part of the burn.':'The surviving stands grow older.',detail:burn.length?`${burn.length} ${burn.length===1?'square burns':'squares burn'} after the ignition.`:'No fire moves across the landscape.',fire,lines:x.lines,focusCells:x.newFuel.length?x.newFuel:[...(fire.burned_cells||[])],skipFire:major||special,turn:r.turn});
      if(i===def){const edges=fire.blocked_edges||[];add({kind:'defense',duration:4,a:x.pre,b:x.end,healthA:r.health_before,health:r.health,chapter:`NIGHT ${r.turn} / THE FIRE LINE`,caption:'The fire reaches the trench and stops.',detail:`${edges.length} recorded ${edges.length===1?'edge holds':'edges hold'}. The forest behind them does not burn.`,fire,lines:x.lines,blocked:edges,focusCells:edges.flat(),turn:r.turn})}
      else if(i===water){add({kind:'defense',duration:3.6,a:x.pre,b:x.end,healthA:r.health_before,health:r.health,chapter:`NIGHT ${r.turn} / RESPONSE TEAM`,caption:'The response team contains the fire.',detail:`The active fire is held to ${burn.length} squares in this game.`,fire,water:true,lines:x.lines,focusCells:burn,turn:r.turn})}
      if(major){
        add({kind:'fuel',duration:3.8,board:x.pre,health:r.health_before,chapter:`NIGHT ${r.turn} / BEFORE THE FIRE`,caption:`Connected fuel now runs through ${direction([...x.corridor])}.`,detail:`The largest fire in this game is about to cross ${burn.length} squares.`,fuel:true,corridor:x.corridor,lines:x.lines,focusCells:[...x.corridor],turn:r.turn});
        add({kind:'ignite',duration:2.3,board:x.pre,health:r.health_before,chapter:`NIGHT ${r.turn} / IGNITION`,caption:ignitionCaption(fire),detail:'The ignition is one point. The connected fuel determines where it can travel.',fire,lines:x.lines,focusCells:[fire.ignition_cell],turn:r.turn});
        add({kind:'majorFire',duration:8.5,board:x.pre,health:r.health_before,chapter:`NIGHT ${r.turn} / FIRE FRONT`,caption:'The fire moves through the recorded landscape.',detail:`Every flame follows the ${fire.waves?.length||1} waves that happened in this game.`,fire,lines:x.lines,focusCells:burn,turn:r.turn});
        add({kind:'aftermath',duration:3.8,a:x.pre,b:x.end,healthA:r.health_before,health:r.health,chapter:`NIGHT ${r.turn} / AFTERMATH`,caption:`${burn.length} squares are left burned.`,detail:`Forest health falls from ${r.health_before}% to ${r.health}%.`,fire,lines:x.lines,focusCells:burn,turn:r.turn});
      }
    });
    add({kind:'ending',duration:3.2,board:model.final,health:model.finalHealth,chapter:'AFTER THE FINAL NIGHT',caption:endingCaption(),detail:model.ending.text||`Forest health ends at ${model.finalHealth}%.`});
    const target=model.criticalIndex>=0?model.criticalIndex:0;add({kind:'rewind',duration:4.5,health:model.rounds[target]?.raw.health_before??model.startHealth,chapter:'REWIND',caption:'Pull every fire back through the forest.',detail:'Return to the first recorded large-fire state.',target});
    if(model.criticalIndex>=0){const x=model.rounds[model.criticalIndex],r=x.raw;add({kind:'critical',duration:4.2,board:x.before,health:r.health_before,chapter:`NIGHT ${r.turn} / EARLIER STATE`,caption:'This is when the game enters its largest-fire band.',detail:'Before this night, every recorded fire stayed below this band.',fuel:true,corridor:x.criticalCorridor,lines:x.linesBefore,focusCells:[...x.criticalCorridor],turn:r.turn})}
    else add({kind:'opening',duration:3,board:model.initial,health:model.startHealth,chapter:'NIGHT ZERO',caption:'This game stayed below the largest-fire band.',detail:'Use the timeline to inspect the spread and every response.',focusCells:starts});total=scenes.at(-1).end;
  }
  function ignitionCaption(f){if(f.ignition_cause==='road_human')return'A human-caused ignition begins beside the road.';if(f.ignition_cause==='spark')return`A spark ignites ${direction([f.ignition_cell])}.`;return'An ignition begins inside the thick stand.'}
  function endingCaption(){const e=model.ending;if(e.result==='win')return`The room wins. ${model.finalHealth}% of the forest remains.`;if(e.reason==='village')return'The fire reaches the homes.';return`The season ends with ${model.finalHealth}% forest health.`}
  const sceneAt=t=>scenes.find(s=>t<s.end)||scenes.at(-1);
  function stateFor(s,p){
    let board=s.board||s.b||model.final,to=s.b,mix=1,fireProgress=0;if(['restore','aftermath','defense'].includes(s.kind)){board=s.a;mix=ease(p)}
    if(s.kind==='growth'){if(s.skipFire){board=s.a;to=s.pre;mix=ease(p)}else if(p<.58){board=s.a;to=s.pre;mix=ease(p/.58)}else{board=s.pre;to=s.b;mix=ease((p-.58)/.42);fireProgress=clamp((p-.55)/.4)}}
    if(s.kind==='defense')fireProgress=clamp(p/.7);if(s.kind==='ignite')fireProgress=.025+clamp(p)*.055;if(s.kind==='majorFire')fireProgress=smoother(clamp(p));if(s.kind==='aftermath')fireProgress=1;
    if(s.kind==='rewind'){const states=[model.final,...model.rounds.slice(s.target).reverse().map(x=>x.before),model.rounds[s.target]?.before||model.initial];board=states[Math.min(states.length-1,Math.floor(p*states.length))];to=null;mix=1}
    const fc=s.focusCells?.length?centroid(s.focusCells):new T.Vector3();return{board,to,mix,fire:s.fire,fireProgress,smokeOnly:s.kind==='aftermath',fuel:!!s.fuel||manualFuel,corridor:s.corridor||new Set(),lines:s.lines||new Set(),blocked:s.blocked||[],water:!!s.water,kind:s.kind,local:p,focus:fc};
  }

  function updateCopy(s,p,health){ui.chapter.textContent=s.chapter||'';ui.line.textContent=s.caption||'';ui.detail.textContent=s.detail||'';ui.health.textContent=Math.round(health)+'%';const turn=s.turn??(/NIGHT (\d+)/.exec(s.chapter||'')?.[1]||0);ui.night.textContent=`${turn} / ${model.rounds.length}`;const f=s.fire,b=f?.burned_cells?.length||0;if(['majorFire','defense','ignite'].includes(s.kind)){ui.telemetry.classList.add('visible');ui.telemetryBody.innerHTML=`<div><i></i>IGNITION&nbsp; <b>${causeName(f?.ignition_cause)}</b></div><div><i></i>FIRE BAND&nbsp; <b>${f?.severity||'–'}</b></div><div><i></i>AREA CROSSED&nbsp; <b>${b} SQUARES</b></div>${s.blocked?.length?`<div><i></i>TRENCH CONTACTS&nbsp; <b>${s.blocked.length}</b></div>`:''}`}else ui.telemetry.classList.remove('visible')}
  const causeName=c=>c==='road_human'?'HUMAN / ROAD':c==='dense_lantana'?'IN THICK STAND':c==='spark'?'SPARK':'NONE';
  function currentTurn(s){return +(s.turn??(/NIGHT (\d+)/.exec(s.chapter||'')?.[1]||(['final','ending'].includes(s.kind)?model.rounds.length:0)))}
  function render(now){
    if(!model||!world)return;let st,health,turn;if(inspector){const x=inspectTurn?model.rounds[inspectTurn-1]:null,board=x?x.end:model.initial,corr=x?(x.corridor||connected(board,'')):connected(board,'');st={board,to:null,mix:1,fire:null,fireProgress:0,fuel:manualFuel,corridor:corr,lines:x?.lines||new Set(),blocked:[],water:false,kind:'inspect',local:0,focus:new T.Vector3()};health=x?x.raw.health:model.startHealth;turn=inspectTurn;updateInspector(x)}
    else{const s=sceneAt(playhead),p=clamp((playhead-s.start)/s.duration);sceneNow=s;sceneProgress=p;health=s.healthA!=null?s.healthA+(s.health-s.healthA)*ease(p):s.health;st=stateFor(s,p);turn=currentTurn(s);updateCopy(s,p,health);ui.scrub.value=Math.round(playhead*1000);ui.clock.textContent=`${fmt(playhead)} / ${fmt(total)}`}
    world.render(st,now/1000,turn);if(audio)audio.update(world.fireAmount);
  }
  function updateInspector(x){const r=x?.raw,h=r?.health??model.startHealth,b=r?.fire?.burned_cells?.length||0,spread=x?.newFuel.length||0,sev=r?.fire?.severity||0;ui.chapter.textContent=inspectTurn?`NIGHT ${r.turn} / EVENT RECORD`:'NIGHT ZERO / EVENT RECORD';ui.line.textContent=inspectTurn?roundCaption(r):'The landscape before the first night.';ui.detail.textContent='Drag to orbit. Scroll to move closer. Use the timeline to change nights.';ui.health.textContent=h+'%';ui.night.textContent=`${inspectTurn} / ${model.rounds.length}`;ui.trackLabel.textContent=inspectTurn?`NIGHT ${r.turn}`:'STARTING LANDSCAPE';ui.clock.textContent=`${inspectTurn} / ${model.rounds.length}`;ui.inspectTitle.textContent=inspectTurn?`Night ${r.turn}`:'Night zero';ui.facts.innerHTML=`<div class="fact"><b>${h}%</b><span>FOREST HEALTH</span></div><div class="fact"><b>${spread}</b><span>NEW INVASION</span></div><div class="fact ember"><b>${b}</b><span>SQUARES BURNED</span></div><div class="fact"><b>${sev||'–'}</b><span>FIRE BAND</span></div>`;ui.inspectNote.textContent=!r?'This is the landscape the room inherited.':r.resilience?.type==='fire_line'?`A fire line was dug. ${r.fire?.blocked_edges?.length||0} fire edges met it.`:r.resilience?.type==='water'?'A response team was ready on this night.':r.resilience?.type==='early_warning'?'Early warning was chosen on this night.':'The room spent this night hunting lantana.'}
  function roundCaption(r){const b=r.fire?.burned_cells?.length||0;if(r.fire?.blocked_edges?.length)return`The trench stops ${r.fire.blocked_edges.length} paths at its edge.`;if(r.fire?.capped_by_water)return`The response team holds the fire to ${b} squares.`;if(b)return`${b} squares burn after the night’s ignition.`;return'No fire moves across the landscape this night.'}
  const fmt=v=>{v=Math.max(0,Math.round(v));return`${Math.floor(v/60)}:${String(v%60).padStart(2,'0')}`};
  function loop(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(playing&&!inspector){playhead+=dt;if(playhead>=total){playhead=total;enterInspector(model.criticalIndex>=0?model.criticalIndex+1:model.rounds.length)}}render(now);requestAnimationFrame(loop)}
  function setPlaying(v){playing=v;ui.playIcon.classList.toggle('pause',v);ui.play.setAttribute('aria-label',v?'Pause replay':'Play replay')}
  function resetScrub(){ui.scrub.min=0;ui.scrub.max=Math.round(total*1000);ui.scrub.step=1;ui.scrub.value=Math.round(playhead*1000);ui.trackLabel.textContent='RECONSTRUCTION'}
  function enterInspector(turn){inspector=true;inspectTurn=clamp(turn,0,model.rounds.length);setPlaying(false);ui.inspect.classList.add('visible');ui.scrub.min=0;ui.scrub.max=model.rounds.length;ui.scrub.step=1;ui.scrub.value=inspectTurn}
  function exitInspector(){inspector=false;ui.inspect.classList.remove('visible');resetScrub()}
  ui.play.onclick=()=>{if(inspector){exitInspector();if(playhead>=total)playhead=0;setPlaying(true)}else setPlaying(!playing)};ui.restart.onclick=()=>{exitInspector();playhead=0;manualFuel=false;ui.fuel.classList.remove('active');setPlaying(true)};
  ui.fuel.onclick=()=>{manualFuel=!manualFuel;ui.fuel.classList.toggle('active',manualFuel);toast(manualFuel?'Fuel scan active':'Fuel scan off')};
  ui.scrub.addEventListener('input',()=>{if(inspector)inspectTurn=+ui.scrub.value;else{playhead=+ui.scrub.value/1000;setPlaying(false)}});
  addEventListener('keydown',e=>{if(e.key===' '){e.preventDefault();ui.play.click()}if(e.key==='ArrowLeft'){if(inspector){inspectTurn=Math.max(0,inspectTurn-1);ui.scrub.value=inspectTurn}else playhead=Math.max(0,playhead-2)}if(e.key==='ArrowRight'){if(inspector){inspectTurn=Math.min(model.rounds.length,inspectTurn+1);ui.scrub.value=inspectTurn}else playhead=Math.min(total,playhead+2)}if(e.key.toLowerCase()==='f')ui.fuel.click()});
  ui.canvas.addEventListener('pointerdown',e=>{if(inspector){drag={x:e.clientX,y:e.clientY,yaw:orbit.yaw,pitch:orbit.pitch};ui.canvas.setPointerCapture(e.pointerId)}});ui.canvas.addEventListener('pointermove',e=>{if(drag){orbit.yaw=drag.yaw-(e.clientX-drag.x)*.006;orbit.pitch=clamp(drag.pitch+(e.clientY-drag.y)*.004,.14,1.15)}});ui.canvas.addEventListener('pointerup',()=>drag=null);ui.canvas.addEventListener('wheel',e=>{if(inspector){e.preventDefault();orbit.distance=clamp(orbit.distance+e.deltaY*.025,18,85)}},{passive:false});
  function toast(s){ui.toast.textContent=s;ui.toast.classList.add('show');setTimeout(()=>ui.toast.classList.remove('show'),1600)}

  class Soundscape{
    constructor(){const A=window.AudioContext||window.webkitAudioContext;this.ctx=new A();this.master=this.ctx.createGain();this.master.gain.value=.48;this.master.connect(this.ctx.destination);const len=this.ctx.sampleRate*3,buf=this.ctx.createBuffer(1,len,this.ctx.sampleRate),a=buf.getChannelData(0);for(let i=0;i<len;i++)a[i]=(Math.random()*2-1)*(.55+.45*Math.sin(i*.00017));this.wind=this.ctx.createBufferSource();this.wind.buffer=buf;this.wind.loop=true;this.windFilter=this.ctx.createBiquadFilter();this.windFilter.type='lowpass';this.windFilter.frequency.value=620;this.windGain=this.ctx.createGain();this.windGain.gain.value=.07;this.wind.connect(this.windFilter).connect(this.windGain).connect(this.master);this.wind.start();this.fire=this.ctx.createBufferSource();this.fire.buffer=buf;this.fire.loop=true;this.fireFilter=this.ctx.createBiquadFilter();this.fireFilter.type='bandpass';this.fireFilter.frequency.value=1700;this.fireFilter.Q.value=.7;this.fireGain=this.ctx.createGain();this.fireGain.gain.value=0;this.fire.connect(this.fireFilter).connect(this.fireGain).connect(this.master);this.fire.start();this.drone=this.ctx.createOscillator();this.drone.type='sine';this.drone.frequency.value=43;this.droneGain=this.ctx.createGain();this.droneGain.gain.value=.025;this.drone.connect(this.droneGain).connect(this.master);this.drone.start();this.lastFire=0;this.on=true}
    impact(){const t=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type='sine';o.frequency.setValueAtTime(61,t);o.frequency.exponentialRampToValueAtTime(31,t+.85);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.18,t+.025);g.gain.exponentialRampToValueAtTime(.0001,t+1.1);o.connect(g).connect(this.master);o.start(t);o.stop(t+1.15)}
    update(n){const t=this.ctx.currentTime;if(n>0&&!this.lastFire)this.impact();this.lastFire=n;this.fireGain.gain.setTargetAtTime(clamp(n/60,0,.22),t,.25);this.windFilter.frequency.setTargetAtTime(n?920:520,t,.5)}
    toggle(){this.on=!this.on;this.master.gain.setTargetAtTime(this.on ? .48 : 0,this.ctx.currentTime,.15);return this.on}
  }
  ui.sound.onclick=async()=>{if(!audio){try{audio=new Soundscape();await audio.ctx.resume();ui.sound.textContent='Sound on';ui.sound.classList.add('active');toast('Ambient sound on')}catch(e){toast('Audio unavailable')}}else{const on=audio.toggle();ui.sound.textContent=on?'Sound on':'Sound off';ui.sound.classList.toggle('active',on)}};
  function progress(n){ui.loadBar.style.width=n+'%'}
  async function load(){const name=new URLSearchParams(location.search).get('log')||'sample-game.json',paths=location.protocol==='file:'?['../sample-game.json']:['/api/log?file='+encodeURIComponent(name),'../sample-game.json'];let d;for(const p of paths){try{const r=await fetch(p);if(r.ok){d=await r.json();break}}catch(e){}}if(!d&&window.PYROCENE_SAMPLE_GZIP&&window.DecompressionStream){const bytes=Uint8Array.from(atob(window.PYROCENE_SAMPLE_GZIP),c=>c.charCodeAt(0)),stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));d=JSON.parse(await new Response(stream).text())}if(!d){ui.loadText.textContent='Choose a Pyrocene game log to continue.';ui.fileButton.style.display='block';return}progress(12);buildModel(d);makeScenes();await new Promise(r=>requestAnimationFrame(r));world=new Landscape();progress(100);playhead=0;setPlaying(true);resetScrub();setTimeout(()=>{ui.loader.classList.add('done');setTimeout(()=>ui.loader.style.display='none',1100)},450);requestAnimationFrame(loop)}
  ui.fileButton.onclick=()=>ui.fileInput.click();ui.fileInput.onchange=async()=>{try{buildModel(JSON.parse(await ui.fileInput.files[0].text()));makeScenes();world=new Landscape();progress(100);ui.loader.classList.add('done');requestAnimationFrame(loop)}catch(e){ui.loadText.textContent=e.message}};
  load().catch(e=>{console.error(e);ui.loadText.textContent=e.message||'The landscape could not be built.';ui.fileButton.style.display='block'});
})();
