import {SECTORS,createRecord,paintCell,commitRecord,exportRecord,importRecord,simulate,scoreRecord,setWorld,snapshot} from "./memory-model.mjs";
const $=id=>document.getElementById(id),map=$("map"),ctx=map.getContext("2d"),teamFire=$("team-fire"),teamCtx=teamFire.getContext("2d"),referenceFire=$("reference-fire"),referenceCtx=referenceFire.getContext("2d"),cell=map.width/6,query=new URLSearchParams(location.search),reducedMotion=matchMedia("(prefers-reduced-motion: reduce)").matches;
let record=createRecord(),selected=14,history=null,worldReady=false,ghost=null,compareRecord=null,animation=0,animationStart=0,scenarioCache=null,ignitionId=null;
const active=id=>SECTORS[id]?.active;
for(const sector of SECTORS.filter(sector=>sector.active))$("sector-picker").add(new Option(sector.label,String(sector.id)));
const estimate=marks=>marks.includes("damp")?[marks.includes("invasive")?.68:.42,.82]:marks.includes("dry")?[.84,.2]:marks.includes("invasive")?[.72,.5]:[.6,.48];
function currentIgnition(){return ignitionId;}
function paintColour(g){if(!g)return "rgba(255,249,232,.57)";const marks=g.tags||[];if(marks.includes("damp"))return "rgba(85,127,160,.64)";if(marks.includes("dry"))return "rgba(200,91,69,.68)";if(marks.includes("invasive"))return "rgba(177,78,109,.64)";return `hsla(${116-g.moisture*48},36%,${84-g.fuel*24}%,.72)`;}
function drawHistory(){const values=history?.layers?.annual_burned_2023?.values,mask=history?.scan_occupancy?.values;if(!$("show-history").checked||!Array.isArray(values)||values.length!==900||!Array.isArray(mask)||mask.length!==900)return;ctx.fillStyle="rgba(116,62,45,.28)";for(let y=0;y<30;y++)for(let x=0;x<30;x++)if(mask[y*30+x]&&values[y*30+x])ctx.fillRect(x*24,y*24,24,24);}
function drawTagMarks(g,x,y){if(!g)return;const symbols={invasive:"v",disturbance:"×",exposed:"+",ignition:"F",people:"p",habitat:"h",uncertain:"?"};let at=0;ctx.fillStyle="#173c35";ctx.font="12px sans-serif";for(const tag of g.tags||[]){if(!symbols[tag])continue;ctx.fillText(symbols[tag],x+53+(at%3)*18,y+34+Math.floor(at/3)*15);at++;}ctx.font="16px Georgia,serif";}
function draw(){
  ctx.clearRect(0,0,map.width,map.height);if(ghost?.complete){ctx.globalAlpha=.13;ctx.drawImage(ghost,0,0,map.width,map.height);ctx.globalAlpha=1;}
  const ignition=record.committed?currentIgnition():null;
  for(const s of SECTORS){const x=s.c*cell,y=s.r*cell,g=record.cells[s.id];ctx.fillStyle=!s.active?"rgba(185,185,168,.7)":paintColour(g);ctx.fillRect(x,y,cell,cell);if(!s.active){ctx.save();ctx.strokeStyle="#77786b";for(let d=-cell;d<cell*2;d+=15){ctx.beginPath();ctx.moveTo(x+d,y);ctx.lineTo(x+d-cell,y+cell);ctx.stroke();}ctx.restore();}ctx.strokeStyle="#285647";ctx.strokeRect(x,y,cell,cell);if(g?.tags?.includes("uncertain")){ctx.setLineDash([5,4]);ctx.strokeRect(x+5,y+5,cell-10,cell-10);ctx.setLineDash([]);}ctx.fillStyle="#173c35";ctx.fillText(s.label,x+7,y+16);drawTagMarks(g,x,y);if(s.id===ignition)ctx.fillText("I",x+cell-16,y+16);}
  drawHistory();const s=SECTORS[selected];if(s){ctx.strokeStyle="#c88e4c";ctx.lineWidth=3;ctx.strokeRect(s.c*cell+2,s.r*cell+2,cell-4,cell-4);ctx.lineWidth=1;}ctx.fillStyle="#173c35";ctx.fillText("N",8,14);
}
function tags(){return [...document.querySelectorAll("fieldset input:checked")].map(input=>input.value);}
function editor(){const g=record.cells[selected],marks=g?.tags||[];$("sector-picker").value=String(selected);$("fuel").value=Math.round((g?.fuel??.5)*100);$("moisture").value=Math.round((g?.moisture??.5)*100);$("confidence").value=Math.round((g?.confidence??.5)*100);$("why").value=g?.why||"";document.querySelectorAll("fieldset input").forEach(input=>input.checked=marks.includes(input.value));$("selected").textContent=`${SECTORS[selected].label} ${g?"recollected":"not observed"}. Not observed is unknown, not damp.`;setLocked(record.committed);}
function setLocked(locked){$("editor").querySelectorAll("input,textarea,button").forEach(el=>el.disabled=locked);$("team").disabled=locked;$("commit").disabled=locked||!worldReady;}
function save(){localStorage.setItem("pyrocene-memory-lab",JSON.stringify(record));}
function teamPaint(){const marks=tags(),simple=estimate(marks),fine=$("fine-tune").open;return {fuel:fine?+$('fuel').value/100:simple[0],moisture:fine?+$('moisture').value/100:simple[1],confidence:fine?+$('confidence').value/100:.5,why:$("why").value,tags:marks};}
map.onclick=event=>{if(!worldReady)return;const box=map.getBoundingClientRect(),id=Math.floor((event.clientY-box.top)*6/box.height)*6+Math.floor((event.clientX-box.left)*6/box.width);if(active(id)){selected=id;editor();draw();}};
$("sector-picker").onchange=event=>{selected=Number(event.target.value);editor();draw();};
$("paint").onclick=()=>{try{record=paintCell(record,selected,teamPaint());invalidateScenario();save();draw();editor();}catch(error){alert(error.message);}};
$("clear").onclick=()=>{if(record.committed)return;delete record.cells[selected];invalidateScenario();save();draw();editor();};
$("team").oninput=event=>{record.teamName=event.target.value;save();};
function savedLeaders(){try{const current=snapshot();return (JSON.parse(localStorage.getItem("pyrocene-memory-leaderboard"))||[]).filter(item=>item.day===current.day&&item.version===current.version);}catch{return [];}}
function drawLeaders(){const list=savedLeaders();$("leaderboard").replaceChildren(...list.map(item=>{const row=document.createElement("li");row.textContent=`${item.team||"Unnamed team"}: ${item.overall}% overall`;return row;}));}
function rememberLeader(score,teamRecord=record){const current=snapshot(),entry={team:teamRecord.teamName,overall:Math.round(score.overall*100),stamp:JSON.stringify(teamRecord.cells),day:current.day,version:current.version};const next=[entry,...savedLeaders().filter(item=>item.team!==entry.team)].sort((a,b)=>b.overall-a.overall).slice(0,3);localStorage.setItem("pyrocene-memory-leaderboard",JSON.stringify(next));}
function invalidateScenario(){scenarioCache=null;}
function scenario(){if(!scenarioCache){const team=simulate(record),reference=simulate(null),score=scoreRecord(record,{teamResult:team,referenceResult:reference}),compareScore=compareRecord?scoreRecord(compareRecord):null;scenarioCache={team,reference,score,compareScore};}return scenarioCache;}
$("commit").onclick=()=>{try{record=commitRecord(record);invalidateScenario();save();const score=scenario().score;rememberLeader(score);$("status").textContent="Committed. Reference revealed.";openFireDialog();draw();editor();}catch(error){alert(error.message);}};
function paintArrival(context,arrival,at,burned){const side=context.canvas.width/60;context.clearRect(0,0,context.canvas.width,context.canvas.height);for(let i=0;i<3600;i++){const x=(i%60)*side,y=Math.floor(i/60)*side,sector=Math.floor(i/60/10)*6+Math.floor(i%60/10);context.fillStyle=!SECTORS[sector].active?"#b9b6a5":arrival[i]!==null&&arrival[i]<=at?burned:"#dfe8cf";context.fillRect(x,y,side,side);}context.save();context.strokeStyle="#285647";for(const sector of SECTORS)context.strokeRect(sector.c*10*side,sector.r*10*side,10*side,10*side);context.fillStyle="#173c35";context.font=`${Math.max(11,side*2)}px Georgia,serif`;context.fillText("N",5,Math.max(14,side*2));context.restore();}
function drawFire(){if(!record.committed)return;const cached=scenario(),at=+$("time").value/100*cached.team.duration;paintArrival(teamCtx,cached.team.arrival,at,"#a46c9b");paintArrival(referenceCtx,cached.reference.arrival,at,"#d9ad4d");$("minute-label").textContent=`${at.toFixed(1)} of ${cached.team.duration} minutes`;const score=cached.score;$("score").textContent=`Observed ${score.observed}/${score.active}. Reconstruction ${Math.round(score.reconstruction*100)}%. Arrival agreement ${Math.round(score.burnPrediction*100)}%. Overall ${Math.round(score.overall*100)}%.`;drawLeaders();if(compareRecord){const other=cached.compareScore;$("comparison").textContent=`Comparison: ${compareRecord.teamName||"imported team"} mapped ${other.observed}/${other.active}, with ${Math.round(other.overall*100)}% overall. Same training reference, ignition, and weather.`;}}
function openFireDialog(){if(!record.committed)return;$("result").hidden=false;$("open-fire").hidden=false;drawFire();if(!$("fire-dialog").open)$("fire-dialog").showModal();}
function stopAnimation(){if(animation){cancelAnimationFrame(animation);animation=0;$("play").textContent="Play fire";}}
function animateFire(now){const value=Math.min(100,(now-animationStart)/12000*100);$("time").value=String(value);drawFire();if(value>=100){stopAnimation();return;}animation=requestAnimationFrame(animateFire);}
$("time").oninput=()=>{stopAnimation();drawFire();};$("play").onclick=()=>{if(animation){stopAnimation();return;}if(+$("time").value>=100)$("time").value="0";animationStart=performance.now()-(+$("time").value/100*12000);$("play").textContent="Pause fire";animation=requestAnimationFrame(animateFire);};$("print").onclick=()=>window.print();$("print-blank").onclick=()=>window.open("memory.html?blank=1&print=1","_blank");
$("open-fire").onclick=openFireDialog;$("close-fire").onclick=()=>{$("fire-dialog").close();stopAnimation();};$("export-dialog").onclick=()=>$("export").click();
$("export").onclick=()=>{const anchor=document.createElement("a");anchor.href=URL.createObjectURL(new Blob([exportRecord(record)],{type:"application/json"}));anchor.download="memory-map.json";anchor.click();setTimeout(()=>URL.revokeObjectURL(anchor.href),500);};
async function readMapFile(file){if(!file)throw Error("Choose a map JSON file");if(file.size>256*1024)throw Error("Memory lab: map JSON must be 256 KB or smaller");return importRecord(await file.text());}
$("import").onchange=async event=>{try{const candidate=await readMapFile(event.target.files[0]);record=candidate;invalidateScenario();$("team").value=record.teamName||"";$("status").textContent=record.committed?"Imported committed map":"Imported paper map";$("result").hidden=!record.committed;$("open-fire").hidden=!record.committed;save();if(record.committed)openFireDialog();draw();editor();}catch(error){alert(error.message);}};
$("compare").onchange=async event=>{try{const candidate=await readMapFile(event.target.files[0]);if(!candidate.committed)throw Error("Choose a committed team map for comparison");compareRecord=candidate;rememberLeader(scoreRecord(candidate),candidate);invalidateScenario();if(!record.committed){$("comparison").textContent="Commit this map to compare both teams against the same training reference.";}else drawFire();}catch(error){alert(error.message);}};
$("photo").onchange=event=>{const file=event.target.files[0],box=$("photo-box"),preview=$("photo-preview");if(!file){box.hidden=true;return;}preview.src=URL.createObjectURL(file);box.hidden=false;$("photo-note").textContent="This photo stays in this browser tab. It is not uploaded or interpreted.";};
$("manual-trace").onchange=event=>{$("photo-note").textContent=event.target.checked?"Manual tracing confirmed. This photo stays in this browser tab and is not interpreted.":"This photo stays in this browser tab. It is not uploaded or interpreted.";};
$("history").onclick=async()=>{try{const candidate=await (await fetch("assets/history.json")).json(),burn=candidate?.layers?.annual_burned_2023?.values,mask=candidate?.scan_occupancy?.values;if(!Array.isArray(burn)||burn.length!==900||!Array.isArray(mask)||mask.length!==900)throw Error("invalid history mask");history=candidate;$("history-toggle").hidden=false;$("history-note").textContent="2023 mapped fire loaded as separate evidence. It does not supply an observed spread path, and the scan predates it by six years.";draw();}catch{$("history-note").textContent="Historical evidence is unavailable or has an invalid footprint mask.";}};$("show-history").onchange=draw;
async function start(){
  try{const {worldAtDay,PROVENANCE,SCENARIO_SEED}=await import("./living-landscape.mjs"),day=3,version=`${PROVENANCE.schema}:${SCENARIO_SEED}:${PROVENANCE.worldVersion}`,world=worldAtDay(day);setWorld(world,{day,version});ignitionId=world.find(cell=>cell.ignition)?.id??null;record=createRecord();worldReady=true;$("snapshot-label").textContent=`Closing field day: Day ${day}. Every team compares this same scenario snapshot.`;$("print-snapshot").textContent=`Closing field day: Day ${day}`;if(reducedMotion)$("play").setAttribute("aria-label","Play fire manually. Animation does not start automatically.");}catch(error){$("status").textContent="Training world unavailable. This lab cannot start.";setLocked(true);console.error(error);return;}
  ghost=new Image();ghost.onload=draw;ghost.src="assets/forest-overhead.jpg";
  if(!query.has("blank"))try{const saved=JSON.parse(localStorage.getItem("pyrocene-memory-lab"));if(saved)record=importRecord(JSON.stringify(saved));}catch{}$("team").value=record.teamName||"";$("status").textContent=record.committed?"Committed map restored":"Paper map ready";$("result").hidden=!record.committed;$("open-fire").hidden=!record.committed;draw();editor();if(record.committed)openFireDialog();if(query.has("print"))setTimeout(()=>window.print(),250);
}
start();
