#!/usr/bin/env python3
"""Emit an apply_patch patch for a compact GUYADIV-derived teaching catalogue.

Source: Sabatier et al., GUYADIV v2, DOI 10.23708/RLYCVQ, CC BY 4.0.
Download https://dataverse.ird.fr/api/access/datafile/49434 separately.
Requires openpyxl. No original survey or source workbook is rewritten.
"""
import collections
import hashlib
import json
import re
import statistics
from pathlib import Path
import openpyxl

ROOT=Path(__file__).resolve().parent
SOURCE=Path('/mnt/seagate/models/pyrocene/stage4/research/guyadiv/GUYADIV_database.xlsx')


def number(v):
    try:return float(v)
    except (ValueError,TypeError):return None


def build():
    wb=openpyxl.load_workbook(SOURCE,read_only=True,data_only=True)
    plots=list(wb['plots'].iter_rows(min_row=2,max_col=21,values_only=True))
    fixed={r[0]:number(r[11]) for r in plots if r[9]=='exhaustive' and r[17]=='Old-growth' and r[19]=='10 cm' and number(r[11]) and number(r[11])>=.25}
    sizes=collections.defaultdict(list);records=collections.defaultdict(list);density=collections.Counter()
    families={};dbh_all=[];valid_byplot=collections.Counter();rows=0
    for r in wb['trees'].iter_rows(min_row=2,values_only=True):
        rows+=1;dbh=number(r[23])
        if r[1] in fixed and dbh is not None and dbh>=10:
            density[r[1]]+=1;dbh_all.append(dbh)
        # Species rank only; omit uncertain identifications and missing names.
        if r[12]!='no' or not isinstance(r[15],str) or not re.fullmatch(r'[A-Z][a-z]+ [a-z-]+',r[15]):continue
        name=r[15];records[name].append(r[1]);families[name]=r[13]
        if dbh is not None and dbh>=10:sizes[name].append(dbh)
    old={s['id'] for s in json.loads((ROOT/'field-catalogue.json').read_text())['species']}
    names=[n for n in sorted(records,key=lambda n:(-len(records[n]),n)) if n.lower().replace(' ','_') not in old and sizes[n]][:96]
    rows_out=[]
    for name in names:
        ds=sorted(sizes[name]);rows_out.append([name,families[name],len(records[name]),len(set(records[name])),round(statistics.median(ds),1),round(ds[int((len(ds)-1)*.9)],1)])
    ds=sorted(dbh_all);densities=sorted(density[p]/area for p,area in fixed.items() if density[p])
    profile={'source':'Sabatier et al. (2024), GUYADIV v2','url':'https://doi.org/10.23708/RLYCVQ','license':'CC BY 4.0','workbookSha256':hashlib.sha256(SOURCE.read_bytes()).hexdigest(),
             'workbookTreeRows':rows,'densityPlots':len(densities),'densityFilter':'Exhaustive old-growth plots >=0.25 ha with a 10 cm threshold; numeric census-1 DBH >=10 cm only. PCQ samples and recruits without first-census DBH excluded.',
             'medianStemsPerHa':round(statistics.median(densities)), 'densityP10':round(densities[int((len(densities)-1)*.1)]),'densityP90':round(densities[int((len(densities)-1)*.9)]),
             'dbhQuantilesCm':[round(ds[int((len(ds)-1)*q)],1) for q in [0,.1,.25,.5,.75,.9,.95,.99]],
             'selection':'96 frequent confidently named species, excluding the original catalogue. Frequencies combine sampling designs and are not regional abundance estimates.'}
    return ('// Generated by prepare_inventory_flora.py. Source facts, not map placements.\n'
            '// Sabatier et al., GUYADIV v2, CC BY 4.0. DOI 10.23708/RLYCVQ.\n'
            '// Rows: scientific name, family, records, plots, median DBH, 90th percentile DBH (cm).\n'
            'export const INVENTORY_TREES = [\n'+''.join('  '+json.dumps(r,ensure_ascii=False)+',\n' for r in rows_out)+'];\n'
            'export const INVENTORY_PROFILE = '+json.dumps(profile,ensure_ascii=False,indent=2)+';\n')


if __name__=='__main__':
    text=build();target=ROOT/'inventory-trees.mjs'
    print('*** Begin Patch')
    if target.exists():
        print('*** Update File: '+str(target));print('@@')
        for line in target.read_text().splitlines():print('-'+line)
    else:print('*** Add File: '+str(target))
    for line in text.splitlines():print('+'+line)
    print('*** End Patch')
