import test from "node:test";
import assert from "node:assert/strict";
import {worldAtDay,PROVENANCE,SCENARIO_SEED} from "./living-landscape.mjs";
import {MEMORY_VERSION,createRecord,paintCell,referenceWorld,scoreRecord,simulate,importRecord,exportRecord,SECTORS,setWorld} from "./memory-model.mjs";

const DAY=3, SNAPSHOT_VERSION=`${PROVENANCE.schema}:${SCENARIO_SEED}:${PROVENANCE.worldVersion}`;
const WORLD=worldAtDay(DAY);
setWorld(WORLD,{day:DAY,version:SNAPSHOT_VERSION});
function perfect(){let record=createRecord("perfect");for(const cell of referenceWorld())if(cell.active)record=paintCell(record,cell.id,{fuel:cell.fuel,moisture:cell.moisture,tags:cell.exposure>.5?["exposed"]:[]});return record;}
test("perfect mapping beats all wet with the real declared world",()=>{const exact=perfect();let wet=createRecord();for(const sector of SECTORS.filter(s=>s.active))wet=paintCell(wet,sector.id,{fuel:.05,moisture:1});assert.equal(scoreRecord(exact).reconstruction,1);assert.ok(scoreRecord(exact).reconstruction>scoreRecord(wet).reconstruction);assert.ok(scoreRecord(exact).burnPrediction>scoreRecord(wet).burnPrediction);});
test("reference simulation uses real WORLD and has a continuous deterministic fine arrival",()=>{const reference=simulate(null),activeArrivals=reference.arrival.filter(value=>value!==null);assert.equal(reference.ignition,33);assert.ok(activeArrivals.length>100);assert.ok(new Set(activeArrivals).size>100,"fine solver should not ignite an entire sector simultaneously");assert.deepEqual(simulate(null).arrival,reference.arrival);});
test("team input changes spread while declared ignition and weather stay shared",()=>{const exact=perfect(),changed=paintCell(exact,13,{fuel:.05,moisture:1,tags:["damp"]});assert.notDeepEqual(simulate(exact).arrival,simulate(changed).arrival);assert.equal(simulate(exact).ignition,simulate(changed).ignition);assert.equal(simulate(exact).weather,simulate(changed).weather);});
test("remembered exposure changes Rothermel wind reduction without hidden reference exposure",()=>{const exact=perfect(),sheltered=paintCell(exact,13,{fuel:WORLD[13].fuel,moisture:WORLD[13].moisture,tags:[]});assert.notDeepEqual(simulate(exact).arrival,simulate(sheltered).arrival);});
test("unknown cells remain a neutral uncertainty rather than a wet firebreak",()=>{const blank=simulate(createRecord());assert.ok(blank.arrival.filter(value=>value!==null).length>100);});
test("zero remembered fuel is a barrier while all-wet mapping misses the reference route",()=>{const exact=perfect(),blocked=paintCell(exact,33,{fuel:0,moisture:1,tags:["damp"]});assert.equal(simulate(blocked).arrival.filter(value=>value!==null).length,0);let wet=createRecord();for(const sector of SECTORS.filter(s=>s.active))wet=paintCell(wet,sector.id,{fuel:.05,moisture:1,tags:["damp"]});assert.ok(simulate(wet).arrival.filter(value=>value!==null).length<simulate(exact).arrival.filter(value=>value!==null).length/10);});
test("imports validate text, marks, cell shape, and the fixed Day 3 snapshot",()=>{const record=perfect();assert.deepEqual(importRecord(exportRecord(record)),record);const base={version:MEMORY_VERSION,snapshotDay:DAY,snapshotVersion:SNAPSHOT_VERSION};assert.throws(()=>importRecord(JSON.stringify({...base,cells:{99:{fuel:.2,moisture:.2}}})),/invalid sector/);assert.throws(()=>importRecord(JSON.stringify({...base,cells:{13:null}})),/need fuel/);assert.throws(()=>importRecord(JSON.stringify({...base,cells:{13:{fuel:.2,moisture:.2,tags:["answer-key"]}}})),/invalid mark/);assert.throws(()=>importRecord(JSON.stringify({...base,snapshotDay:2,cells:{}})),/different landscape snapshot/);});
